volumes:
  postgres-data:
    name: ${PROJECTNAME}-postgres-data
    driver: local

services:
  app:
    container_name: ${PROJECTNAME}-app
    build:
      dockerfile: Dockerfile
      context: app
      target: production
      args:
        GRPCPORT: ${GRPCPORT}
        GRPCSSLPORT: ${GRPCSSLPORT}
        OPSPORT: ${OPSPORT}
        HTTP: ${HTTP}
        HTTPS: ${HTTPS}
    working_dir: /app
    command: "./app"

  tool:
    container_name: ${PROJECTNAME}-tool
    volumes:
      - "./app:/app"
    build:
      dockerfile: Dockerfile
      context: app
      target: builder
      args:
        GRPCPORT: ${GRPCPORT}
        GRPCSSLPORT: ${GRPCSSLPORT}
        OPSPORT: ${OPSPORT}
        HTTP: ${HTTP}
        HTTPS: ${HTTPS}
        USERID: ${USERID}
        GROUPID: ${GROUPID}
        USERNAME: ${USERNAME}
    command: "sh -c 'while true; do sleep 1; done'"

  postgres:
    ports:
      - "${OUT_POSTGRES}:5432"
    container_name: ${PROJECTNAME}-db
    image: postgres:17.4
    environment:
      - "PGDATA=/data"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=database"
      - "POSTGRES_USER=user"
    volumes:
      - "postgres-data:/data"
