volumes:
  prometheus-data:
    name: ${PROJECTNAME}-prometheus-data
    driver: local
  grafana-data:
    name: ${PROJECTNAME}-grafana-data
    driver: local
  postgres-data:
    name: ${PROJECTNAME}-postgres-data
    driver: local

networks:
  default:
    name: ${PROJECTNAME}-network

services:
#  app:
#    container_name: ${PROJECTNAME}-app
#    build:
#      dockerfile: Dockerfile
#      context: app
#      target: production
#      args:
#        GRPCPORT: ${GRPCPORT}
#        GRPCSSLPORT: ${GRPCSSLPORT}
#        OPSPORT: ${OPSPORT}
#        HTTP: ${HTTP}
#        HTTPS: ${HTTPS}
#    working_dir: /app
#    command: "./app"
#    networks:
#      - default
#  frontend:
#    container_name: ${PROJECTNAME}-frontend
#    build:
#      dockerfile: Dockerfile
#      context: frontend
#    working_dir:
#      /app
#    volumes:
#      - "./frontend:/app"
#    command: "sh -c 'while true; do sleep 1; done'"
#    ports:
#      - "5173:5173"
#    networks:
#      - default

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: ${PROJECTNAME}-prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./metric/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - "prometheus-data:/prometheus/"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - default

  #admin:admin
  grafana:
    image: grafana/grafana-oss
    container_name: ${PROJECTNAME}-grafana
    environment:
      GF_FEATURE_TOGGLES_ENABLE: publicDashboards
    volumes:
      - "grafana-data:/var/lib/grafana/"
      - ./metric/grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - default

  jaeger:
    container_name: ${PROJECTNAME}-jaeger
    image: jaegertracing/all-in-one:1.45
    ports:
      - "${JAEGER_UI_PORT}:16686"  # Jaeger UI
      - "${JAEGER_HTTP_COLLECTOR_PORT}:14268"  # HTTP collector
      - "${JAEGER_UDP_COLLECTOR_PORT}:6831/udp" # Agent UDP
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - default

  tool:
    container_name: ${PROJECTNAME}-tool
    volumes:
      - "./app:/app"
    build:
      dockerfile: Dockerfile
      context: app
      target: builder
      args:
        GRPCPORT: ${GRPCPORT}
        GRPCSSLPORT: ${GRPCSSLPORT}
        OPSPORT: ${OPSPORT}
        HTTP: ${HTTP}
        HTTPS: ${HTTPS}
        USERID: ${USERID}
        GROUPID: ${GROUPID}
        USERNAME: ${USERNAME}
    command: "sh -c 'while true; do sleep 1; done'"
    networks:
      - default

  postgres:
    ports:
      - "${OUT_POSTGRES}:5432"
    container_name: ${PROJECTNAME}-db
    image: postgres:17.4
    environment:
      - "PGDATA=/data"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=database"
      - "POSTGRES_USER=user"
    volumes:
      - "postgres-data:/data"
    networks:
      - default
