db:
  host: "localhost"
  port: 9432
  username: "user"
  password: "password"
  database: "database"
addr_metric: ":9090"
addr_grpc: ":8502"
addr_http: ":8503"
telegram_bot:
  token: "7358655876:AAF3QEyTt1wp31TpM03yFigx9DHcO63_7wI" #t.me/AtomVPNProjectSuperBot
mailer:
  smtp:
    yandex1:
      weight: 100
      host: "smtp.yandex.com"
      port: 465
      username: "dvzamiatin@yandex.ru"
      password: "ugiriayxnmundnex"
      sender: "dvzamiatin@yandex.ru"
      ssl: true
      timeout: "1s"
    yandex2:
      weight: 10
      host: "smtp.yandex.com"
      port: 465
      username: "dvzamiatin@yandex.ru"
      password: "ugiriayxnmundnex"
      sender: "dvzamiatin@yandex.ru"
      ssl: true
      timeout: "1s"
